version: '3.1'

services:

  app:
    build: .
    container_name: app

    env_file:
      - .env
    environment:
      DATABASE_URL: 'mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin'

    volumes:
      - .:/usr/src/app
    ports:
      - 8000:${PORT}
    depends_on: 
      - mongo
    networks:
      - app_network
  mongo:
    image: mongo
    container_name: mongo
    ports: 
      - 27017:27017
    env_file:
      - .env
    networks:
      - app_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on: 
      - mongo
    networks:
      - app_network

networks:
  app_network:
    driver: bridge